#!/bin/bash
# wold_c6
# demo of
# if

echo –n "Enter your favorite color: " 
read -r color
case "$color" in
"blue")  echo "As in My Blue Heaven.";;
"yellow") echo "As in the Yellow Sunset.";;
"red")  echo "As in Red Rover, Red Rover.";;
"orange") echo "As in Autumn has shades of Orange.";;
*) echo "Sorry, I do not know that color.";;
esac

#num_chk=0
#while (( $num_chk <= 5 ))
#do 
#uptime 
#sleep 2
#let num_chk=num_chk+1
#done

#IFS="|"
#for USERS in $(ls -l)
#do
#echo $USERS
#done
#unset IFS="|"

# echo "what is your favorite vegetable?"
# read veg_name
# 
# if test ""
# finish code from Guide to UNIX Using Linux foruth edition in blackboard on page 295

#echo -n "Try to guess my favorite color:  "
#read guess
#while [ "$guess" != "red" ]; do
#echo -n "No, not that one. Try again. "; read guess
#done
